FROM node:18.15.0

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

# Define the variables using ARG
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG JWT_SECRET

# Set the environment variables using the ARG values
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_NAME=${DB_NAME}
ENV JWT_SECRET=${JWT_SECRET}

EXPOSE 3002

CMD ["npm", "start"]
